on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: bundle

      - name: install logstash
        run: |
          set -eu

          wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
          sudo apt-get install apt-transport-https
          echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
          sudo apt-get update && sudo apt-get install logstash
          echo "::add-path::/usr/share/logstash/bin/"

      - run: bundle install --jobs 4 --retry 3 --deployment
      - run: ruby -e 'load "logit/spec/helpers/logstash_helper.rb"; puts(Logstash.new(File.read("logit/aws_logstash.conf")).wait_to_start.parse_line "banana")'
      - run: bundle exec rspec --format d logit/spec/aws_logstash_spec.rb
